### ISSUE TITLE
java.lang.ArithmeticException: long overflow

### ISSUE THREAD

**Issue by book000** [jaoafa/AwayFromKeyboard#9]
```
[21:39:06] [Craft Scheduler Thread - 576 - AwayFromKeyboard/WARN]: [AwayFromKeyboard] Plugin AwayFromKeyboard v2.1.3 generated an exception while executing task 18
java.lang.ArithmeticException: long overflow
        at java.lang.Math.multiplyExact(Math.java:1004) ~[?:?]
        at java.lang.Math.multiplyExact(Math.java:980) ~[?:?]
        at java.time.Duration.toMillis(Duration.java:1227) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.ticks(CraftPlayer.java:2390) ~[paper-1.18.1.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_18_R1.entity.CraftPlayer.sendTitlePart(CraftPlayer.java:2380) ~[paper-1.18.1.jar:git-Paper-160]
        at com.jaoafa.AwayFromKeyboard.Library.AFKPlayer.start(AFKPlayer.java:82) ~[AwayFromKeyboard-v2.1.3.jar:?]
        at com.jaoafa.AwayFromKeyboard.Library.AFKPlayer.start(AFKPlayer.java:56) ~[AwayFromKeyboard-v2.1.3.jar:?]
        at com.jaoafa.AwayFromKeyboard.Task.Task_AFK.run(Task_AFK.java:58) ~[AwayFromKeyboard-v2.1.3.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-160]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.1.jar:git-Paper-160]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.1.jar:git-Paper-160]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by book000** [comment]
#10
